
version: "3"

services:
  app:
    container_name: app-dev-c
    image: app-dev-i
    build:
      context: .
      dockerfile: Dockerfile.yml
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"






