version: "3"

services:
  app:
    build:
      context: app
      dockerfile: ../Dockerfile
    image: vision/app
    command: yarn start
    container_name: vision-app
    restart: on-failure
    env_file: 
      - ".env"
    volumes: 
      - "./app/src:/workspace/src"
